server:
  port: 8080
  servlet:
    context-path: /app
spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:mydb;MODE=PostgreSQL
    username: sa
    password:
  jpa:
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
    generate-ddl: true
  h2:
    console:
      enabled: true

application-description : "Данная документация предназначена для тестового задания, по написанию сервиса обслуживания банковских счетов."
application-version : 0.1.0